hyperskill_project:
  id: 97
  ide_files: https://cogniterra.org/media/attachments/lesson/24741/additional_files.json
  is_template_based: true
  use_ide: true
update_date: "Sun, 12 Jan 2025 14:13:10 UTC"
stages:
  - id: 534
    step: 8799
    is_completed: true
  - id: 535
    step: 8800
    is_completed: true
  - id: 536
    step: 8801
    is_completed: true
  - id: 537
    step: 8802
    is_completed: true
  - id: 538
    step: 8803
    is_completed: true
